### PR TITLE
Feature/plantnet

### PR DESCRIPTION
**Pull request by Zephyr75**
App can now take photos, store them on Firebase and upload them to the Plantnet API

### CODE REVIEW

**Review by Aco-Hub — COMMENTED** [review]
The code is really good and efficient however it lacks some comments.

**Review by Aco-Hub — APPROVED** [review]
The code is perfect.

**Review by Tetardfurieux — COMMENTED** [review]
Good code overall,
You should specify if a variable is private/public, instead of writting "String" only.
Good comments tho, some part of the code is not yet commented.
Fix before merging !

**Review by Tetardfurieux — APPROVED** [review]
Much better this way !
Keep up the good work

**Pull request merged**
